[build]
  publish = "dist"
  command = "npm install -g pnpm && pnpm install && pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"
  port = 5173
  publish = "dist"
